### Register a new user
POST http://127.0.0.1:5000/api/register
Content-Type: application/json

{
  "email": "sudo@example.com",
  "password": "sudo"
}

### Login to get the JWT token
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
  "email": "sudo@example.com",
  "password": "sudo"
}

### Create a blog post (replace <TOKEN> with the JWT token)
POST http://127.0.0.1:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxOTk1NzMxNiwianRpIjoiYzk3MzIxZWQtOWEwYS00NzA0LWExYTItNjFlNzQzMTdlZGJmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN1ZG9AZXhhbXBsZS5jb20iLCJuYmYiOjE3MTk5NTczMTYsImNzcmYiOiJiOWJkZGFmZS1kNDM0LTQ0NjMtOGU5YS1kNjMxYWFkOTg5YzIiLCJleHAiOjE3MTk5NTgyMTZ9.a2Fd8A6z7RXzHM-sBP1gUw3Yr0jE4ANTg4-ig7u073A

{
  "title": "My second Blog Post",
  "content": "This is the content of my first blog post."
}

### Add a comment to a blog post (replace <TOKEN> with the JWT token and <POST_ID> with the post ID)
POST http://127.0.0.1:5000/api/posts/2/comments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxOTk1NzMxNiwianRpIjoiYzk3MzIxZWQtOWEwYS00NzA0LWExYTItNjFlNzQzMTdlZGJmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN1ZG9AZXhhbXBsZS5jb20iLCJuYmYiOjE3MTk5NTczMTYsImNzcmYiOiJiOWJkZGFmZS1kNDM0LTQ0NjMtOGU5YS1kNjMxYWFkOTg5YzIiLCJleHAiOjE3MTk5NTgyMTZ9.a2Fd8A6z7RXzHM-sBP1gUw3Yr0jE4ANTg4-ig7u073A

{
  "content": "This is a comment."
}

### Get comments of a blog post (replace <POST_ID> with the post ID)
GET http://127.0.0.1:5000/api/posts/1/comments
