### Register a new user
POST http://127.0.0.1:5000/api/register
Content-Type: application/json

{
  "email": "sudo@example.com",
  "password": "sudo"
}

### Login to get the JWT token
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
  "email": "sudo@example.com",
  "password": "sudo"
}

### Create a blog post (replace <TOKEN> with the JWT token)
GET  http://127.0.0.1:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDIwNjQ5MywianRpIjoiNzk4YWUyNTItYjI4NC00OTk3LTg1NzYtNjI0Mzk4OTk2MTFmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN1ZG9AZXhhbXBsZS5jb20iLCJuYmYiOjE3MjAyMDY0OTMsImNzcmYiOiI4ZWZmNWMyNC03YTY5LTQxODYtYjA0ZC1lMWM4N2RjNGU2NTYiLCJleHAiOjE3MjAyMDczOTN9.Kmurf-TsjyTy0gnkoMLlzBlPRv3vtnxb05evPytj3XU



{
  "title": "My second Blog Post",
  "content": "This is the content of my first blog post."
}

### Add a comment to a blog post (replace <TOKEN> with the JWT token and <POST_ID> with the post ID)
POST http://127.0.0.1:5000/api/posts/2/comments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDEyOTM3OCwianRpIjoiMDdkZGY2MTYtZmZhZi00MmNjLTlkYTctNjg3ZTEzOTMyNWY2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN1ZG9AZXhhbXBsZS5jb20iLCJuYmYiOjE3MjAxMjkzNzgsImNzcmYiOiJlNjE0Y2NjOS0xOGI2LTQ0MmEtOGIyNi01NjgzMTFiMzExM2EiLCJleHAiOjE3MjAxMzAyNzh9.TxZWQIVYdIE_XmFemNbutzF6qne4ApquMv3xSgDkYSk

{
  "content": "This is a comment."
}

### Get comments of a blog post (replace <POST_ID> with the post ID)
GET http://127.0.0.1:5000/api/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDIwNjQ5MywianRpIjoiNzk4YWUyNTItYjI4NC00OTk3LTg1NzYtNjI0Mzk4OTk2MTFmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InN1ZG9AZXhhbXBsZS5jb20iLCJuYmYiOjE3MjAyMDY0OTMsImNzcmYiOiI4ZWZmNWMyNC03YTY5LTQxODYtYjA0ZC1lMWM4N2RjNGU2NTYiLCJleHAiOjE3MjAyMDczOTN9.Kmurf-TsjyTy0gnkoMLlzBlPRv3vtnxb05evPytj3XU